apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman-cockroachdb-tqja
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman-cockroachdb-tqja
    app.kubernetes.io/part-of: veda-pacman
  name: pacman-cockroachdb-tqja
  namespace: veda2019subs-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: pacman-cockroachdb-tqja
    weight: null
status: {}
